// swift-tools-version: 6.0
import PackageDescription

// All viewer logic lives here so `swift build` / `swift test` work
// headlessly; the Xcode app target (generated by XcodeGen from
// ../project.yml) is a thin shell over ViewerUI.
//
// Layering:
//   CMSLog     — Clang module over ../StructuredLogViewer.NativeBridge's
//                mslog.h (symbols resolved when the app links libmslog.dylib)
//   ViewerCore — platform-neutral models, BinlogEngine protocol, view models;
//                fully unit-testable against MockBinlogEngine
//   BinlogKit  — BinlogSession actor: async Swift wrapper over the C ABI,
//                implements BinlogEngine
//   ViewerUI   — SwiftUI views + AppKit tree (NSOutlineView)
let package = Package(
    name: "StructuredLogViewerKit",
    platforms: [.macOS(.v15)],
    products: [
        .library(name: "ViewerCore", targets: ["ViewerCore"]),
        .library(name: "BinlogKit", targets: ["BinlogKit"]),
        .library(name: "ViewerUI", targets: ["ViewerUI"]),
    ],
    targets: [
        .systemLibrary(name: "CMSLog", path: "Sources/CMSLog"),
        // Link-time no-ops for the C ABI, so ViewerUI can be unit-tested
        // without the NativeAOT dylib. Test-only; never in the app.
        .target(name: "CMSLogStub"),
        .target(name: "ViewerCore"),
        .target(name: "BinlogKit", dependencies: ["CMSLog", "ViewerCore"]),
        .target(name: "ViewerUI", dependencies: ["ViewerCore", "BinlogKit"]),
        .testTarget(name: "ViewerCoreTests", dependencies: ["ViewerCore"]),
        .testTarget(name: "ViewerUITests", dependencies: ["ViewerUI", "ViewerCore", "CMSLogStub"]),
    ],
    swiftLanguageModes: [.v5]
)
